spring:
  application:
    name: bills
  jpa:
    database: POSTGRESQL
    hibernate:
      ddlAuto: validate
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bills
    username: postgres
    password: postgres

server:
  port: 8080